### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by whwh747** [JunyuanDeng/NeRF-LOAM#11]
Hello, thank you for your kind words. To run the demo on a TiTan XP graphics card without encountering a CUDA OOM (Out of Memory) issue at 20 frames, you would need a graphics card with at least how much memory?

**Comment by JunyuanDeng** [comment]
I tested my code with  RTX 3090 and NVIDIA TITAN RTX 24GB, both of which have 24GB memory.

In my personal experience, a GPU with 16GB memory is sufficient.

您好，大概需要16GB的显存，我之前测试都是用24GB显存的卡跑，没什么特别问题

**Comment by whwh747** [comment]
thank you
