### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by whwh747** [JunyuanDeng/NeRF-LOAM#12]
你好   我在kitti数据集上只跑了20帧，下面图片里是生成的文件  我该如何可视化它们  
<img width="235" alt="1702887440300" src="https://github.com/JunyuanDeng/NeRF-LOAM/assets/63688127/9ad9bdff-acc5-4a73-b230-0c8792366f20">

**Comment by JunyuanDeng** [comment]
您好，ply文件是稠密重建结果，可以用meshlab或者open3d打开。

位姿文件frame_poses可以用[evo](https://github.com/MichaelGrupp/evo)这个库进行可视化。
