### ISSUE TITLE
 whether Need groundtruth pose ?

### ISSUE THREAD

**Issue by Zhangjyhhh** [JunyuanDeng/NeRF-LOAM#20]
Hi? thanks for your excellent work!!!
I wonder whether it need groundtruth pose for geting groundtruth SDF.

**Comment by JunyuanDeng** [comment]
Thanks, Zhangjyhhh.

You can read from our paper that we obtained the groundtruth SDF directly from the LiDAR data. Therefore, it doesnot need groundtruth pose for geting groundtruth SDF.
