### ISSUE TITLE
svo init

### ISSUE THREAD

**Issue by whwh747** [JunyuanDeng/NeRF-LOAM#27]
Thanks for your outstanding work. Could you please elaborate on the rationale behind setting the first parameter in svo.init() to 256*256*4?

**Comment by JunyuanDeng** [comment]
Hi, whwh747,

Indeed, 256*256*4 is the maximum number of voxels in one side. The corresponding code could be found [here](https://github.com/JunyuanDeng/NeRF-LOAM/blob/2fe4e8d8dd9a8da12624ba8e8e4f49d851ce8c92/third_party/sparse_octree/src/octree.cpp#L34).

**Comment by whwh747** [comment]
i got it，thank you very much！
