### ISSUE TITLE
eval issue

### ISSUE THREAD

**Issue by whwh747** [JunyuanDeng/NeRF-LOAM#28]
Thank you for your outstanding work! I'd like to ask, do you strictly adhere to the evaluation process of shine-mapping when assessing the results of the code? In other words, do you use eval/evaluator.py in shine-mapping to quantitatively estimate the reconstruction results in the paper?

**Comment by JunyuanDeng** [comment]
Hi,

As we mentioned that we did not use the crop_intersection.py before.

For the left setting, we do the same evaluation process of shine-mapping.

**Comment by whwh747** [comment]
thank you！
