### ISSUE TITLE
Training procedure

### ISSUE THREAD

**Issue by mramezani64** [JunyuanDeng/NeRF-LOAM#3]
The idea of neural SDF for localisation and mapping is interesting. Can you please elaborate more on how the training process is performed? Which dataset you used to train the network, and then when you say "without pre-training," do you mean the network trained on dataset X was used for testing on the other datasets? I couldn't find this part in the paper.

**Comment by JunyuanDeng** [comment]
Hi, 

Actually, the training process is performed on the dataset we want to test. If I want to get the running results on dataset X, the system is training on this dataset. The training process uses the range measurements to train the voxel features and MLP, once we have trained one frame, the pose of the subsequent frame can be inferred from the trained frame by freezing the MLP and feature. Once we get the pose of this subsequent frame, we can use the range measurements of this frame to train the voxel features and MLP again. We iterate this process and in the end, we can get the trained features, MLP, and poses. Such information enables us to get the mesh map.
