### ISSUE TITLE
question about table1

### ISSUE THREAD

**Issue by Zhangjyhhh** [JunyuanDeng/NeRF-LOAM#32]
Hi，thanks for your excellent work!!!!!!
The result on new college dataset in table 1, i want to know the dataset(new college dataset) you used  whether from the script you provide[https://github.com/PRBonn/SHINE_mapping/blob/master/scripts/download_ncd_example.sh](url) ? . the script content is this:
/echo Creating the dataset path...

mkdir -p data
cd data

echo Downloading Newer College dataset, Quad example subset...
wget -O ncd_example.tar.gz -c https://uni-bonn.sciebo.de/s/ZKTMubNY9mqbfwN/download

echo Extracting dataset...
tar -xvf ncd_example.tar.gz

rm ncd_example.tar.gz

cd ../..

**Comment by JunyuanDeng** [comment]
Yes, I used this scripts to download datasets.

**Comment by Zhangjyhhh** [comment]
> Yes, I used this scripts to download datasets.

thanks for your reply
