### ISSUE TITLE
poor result about mesh

### ISSUE THREAD

**Issue by Zhangjyhhh** [JunyuanDeng/NeRF-LOAM#33]
I run your code use default config on new college dataset, but i can not get the same result as table 1 show. By the way, i use the link you provide to evaluate. Here are the evaluation config :
# For NCD
down_sample_vox = 0.02
dist_thre = 0.2
truncation_dist_acc = 0.4
truncation_dist_com = 2.0
 Here are my result:
{'MAE_accuracy (m)': 0.1600144107307643, 'MAE_completeness (m)': 0.19971273194331618, 'Chamfer_L1 (m)': 0.17986357133704023, 'Chamfer_L2 (m)': 0.26092833422825545, 'Precision [Accuracy] (%)': 64.36066911590589, 'Recall [Completeness] (%)': 61.93420844798163, 'F-score (%)': 63.12412939882961, 'Spacing (m)': 0.02, 'Inlier_threshold (m)': 0.2, 'Outlier_truncation_acc (m)': 0.4, 'Outlier_truncation_com (m)': 2.0}

I want upload the mesh i get ,but it seems too large to upload. So i want to know how can i get the same result as you

**Comment by JunyuanDeng** [comment]
Thanks for your attention.

Is mesh that used to evaluate is the one after "key-scan refine"?

**Comment by JunyuanDeng** [comment]
You could upload a screenshot instead of a mesh file so that I can provide more help.

**Comment by Zhangjyhhh** [comment]
> Thanks for your attention.
> 
> Is mesh that used to evaluate is the one after "key-scan refine"?

I use the final_mesh.ply. Is the mesh that used to evaluate is the one after "key-scan refine
![Screenshot from 2024-07-16 12-06-22](https://github.com/user-attachments/assets/2b552328-24e7-4e85-9106-fc07eefaed36)

**Comment by JunyuanDeng** [comment]
Yes, what does mesh looks like?

**Comment by Zhangjyhhh** [comment]
> You could upload a screenshot instead of a mesh file so that I can provide more help.

here are my evaluation screenshot , config screenshoot and mesh screenshot
![2024-07-16 12-24-54 的屏幕截图](https://github.com/user-attachments/assets/212b3827-4733-4f30-8f60-b823d38a6c1d)
![2024-07-16 12-28-46 的屏幕截图](https://github.com/user-attachments/assets/9bed2b8d-f00b-4e23-98e0-bb5344eb39fa)
![2024-07-16 12-28-51 的屏幕截图](https://github.com/user-attachments/assets/169c2e4b-0747-4ba2-a6db-df535e506718)
![Screenshot from 2024-07-16 12-23-00](https://github.com/user-attachments/assets/7e2bcace-8592-4961-b0ca-bfcdb73033db)


> Yes, what is mesh looks like?

here are my evaluation screenshot , config screenshoot and mesh screenshot
![2024-07-16 12-24-54 的屏幕截图](https://github.com/user-attachments/assets/212b3827-4733-4f30-8f60-b823d38a6c1d)
![2024-07-16 12-28-46 的屏幕截图](https://github.com/user-attachments/assets/9bed2b8d-f00b-4e23-98e0-bb5344eb39fa)
![2024-07-16 12-28-51 的屏幕截图](https://github.com/user-attachments/assets/169c2e4b-0747-4ba2-a6db-df535e506718)
![Screenshot from 2024-07-16 12-23-00](https://github.com/user-attachments/assets/7e2bcace-8592-4961-b0ca-bfcdb73033db)

**Comment by Zhangjyhhh** [comment]
> Yes, what is mesh looks like?

By the way, i only change the parameter " read_offset" from  default 5 to1, does it will change mesh quality

**Comment by JunyuanDeng** [comment]
Yes, it would decrese the mesh quality, newer college dataset is collected by handhold devices, which means the lidar is not only suffer from motion distortion but also too dense for the task of reconstruction. Basically, the shape of the mesh is good, but the ground is not flat, that may due to the dense lidar scan and motion distortion. You can try to set "read_offset" to 1 to see the results.

**Comment by Zhangjyhhh** [comment]
> Yes, it would decrese the mesh quality, newer college dataset is collected by handhold devices, which means the lidar is not only suffer from motion distortion but also too dense for the task of reconstruction. Basically, the shape of the mesh is good, but the ground is not flat, that may due to the dense lidar scan and motion distortion. You can try to set "read_offset" to 1 to see the results.

the above result is from read_offset=1, and I will try read_offset=5 later,and thanks for your reply

**Comment by JunyuanDeng** [comment]
Hope you get better results~

**Comment by Zhangjyhhh** [comment]
> Hope you get better results~

This time i get better result same as table 1:
{'MAE_accuracy (m)': 0.12597577918410047, 'MAE_completeness (m)': 0.17532213101945665, 'Chamfer_L1 (m)': 0.15064895510177856, 'Chamfer_L2 (m)': 0.2505973745191964, 'Precision [Accuracy] (%)': 77.41172923137316, 'Recall [Completeness] (%)': 71.95672924778981, 'F-score (%)': 74.58461977342017, 'Spacing (m)': 0.02, 'Inlier_threshold (m)': 0.2, 'Outlier_truncation_acc (m)': 0.4, 'Outlier_truncation_com (m)': 2.0}
Thanks for your quick reply!!!!!

**Comment by JunyuanDeng** [comment]
You even got better results than that in the paper, hahahah
