### ISSUE TITLE
Does this method support low-resolution lidar like VLP-16 or others?

### ISSUE THREAD

**Issue by qpc001** [JunyuanDeng/NeRF-LOAM#4]

**Comment by JunyuanDeng** [comment]
Hi, qpc001

Sorry for the late response, I got Covid these days.

We test our algorithm for velodyne data in one rosbag of Stevens-VLP16-Dataset. The results seem to be good. We are sorry that we cannot provide detailed quantitative or qualitative results for our paper is still under review. 

Thanks for your interest in our work.

**Comment by peterWon** [comment]
> Hi, qpc001
> 
> Sorry for the late response, I got Covid these days.
> 
> We test our algorithm for velodyne data in one rosbag of Stevens-VLP16-Dataset. The results seem to be good. We are sorry that we cannot provide detailed quantitative or qualitative results for our paper is still under review.
> 
> Thanks for your interest in our work.

@JunyuanDeng Hi, can you share the config parameters for VLP16 lidar, thanks.
